package com.uklanafood.delivery;
import android.*;import android.content.*;import android.content.pm.PackageManager;import android.os.*;import android.view.*;import android.widget.*;import androidx.appcompat.app.*;import androidx.core.app.ActivityCompat;import com.google.firebase.messaging.FirebaseMessaging;import org.json.*;
public class MainActivity extends AppCompatActivity{
 LinearLayout list,history,onlineHistory;TextView total,earning,onlineDue,status,name;
 private final Handler h=new Handler(Looper.getMainLooper());
 private final Runnable poll=new Runnable(){@Override public void run(){load();h.postDelayed(this,AppConfig.REFRESH_MS);}};
 protected void onCreate(Bundle b){super.onCreate(b);if(!SessionManager.loggedIn(this)){startActivity(new Intent(this,LoginActivity.class));finish();return;}setContentView(R.layout.activity_main);list=findViewById(R.id.ordersContainer);history=findViewById(R.id.receivedHistoryContainer);total=findViewById(R.id.runningTotal);earning=findViewById(R.id.deliveryEarningTotal);onlineDue=findViewById(R.id.onlineDeliveryDue);onlineHistory=findViewById(R.id.onlineDeliveryHistoryContainer);status=findViewById(R.id.statusText);name=findViewById(R.id.deliveryName);name.setText(SessionManager.name(this)+" • Boy "+SessionManager.priority(this));findViewById(R.id.resetTotalButton).setOnClickListener(v->reset());findViewById(R.id.resetOnlineDeliveryButton).setOnClickListener(v->resetOnlineDelivery());findViewById(R.id.logoutButton).setOnClickListener(v->{SessionManager.clear(this);recreate();});NotificationHelper.channel(this);if(Build.VERSION.SDK_INT>=33&&ActivityCompat.checkSelfPermission(this,Manifest.permission.POST_NOTIFICATIONS)!=PackageManager.PERMISSION_GRANTED)requestPermissions(new String[]{Manifest.permission.POST_NOTIFICATIONS},9);FirebaseMessaging.getInstance().getToken().addOnSuccessListener(t->new Thread(()->{try{ApiClient.post(this,AppConfig.FCM,new JSONObject().put("fcm_token",t));}catch(Exception ignored){}}).start());String m=getIntent().getStringExtra("message");if(m!=null)Toast.makeText(this,m,Toast.LENGTH_LONG).show();load();}
 protected void onResume(){super.onResume();h.postDelayed(poll,12000);}protected void onPause(){super.onPause();h.removeCallbacks(poll);} 
 void load(){new Thread(()->{try{JSONObject d=ApiClient.get(this,AppConfig.DASHBOARD);JSONArray o=ApiClient.get(this,AppConfig.ORDERS).optJSONArray("orders");runOnUiThread(()->render(d,o));}catch(Exception e){runOnUiThread(()->status.setText(e.getMessage()));}}).start();}
 void render(JSONObject d,JSONArray a){total.setText(d.optString("running_total","₹0"));earning.setText(d.optString("delivery_earning_total","₹0"));onlineDue.setText(d.optString("online_delivery_due","₹0"));status.setText("Assigned: "+d.optInt("assigned_count")+" • Delivered: "+d.optInt("delivered_count"));list.removeAllViews();if(a!=null)for(int i=0;i<a.length();i++){JSONObject o=a.optJSONObject(i);TextView v=new TextView(this);v.setPadding(24,20,24,20);v.setText("Order #"+o.optString("number")+"\nRestaurant: "+o.optString("restaurant")+"\nCustomer: "+o.optString("customer_name")+" • "+o.optString("phone")+"\nAddress: "+o.optString("address")+"\n\nItems:\n"+o.optString("items")+"\n\nPayment: "+o.optString("payment_status")+"\nFood / Company Amount: "+o.optString("food_amount")+"\nDelivery Boy Earning: "+o.optString("delivery_boy_earning")+"\nCustomer Total: "+o.optString("customer_total")+"\nCompany Cash to Submit: "+o.optString("collect_amount"));v.setTextSize(16);v.setBackgroundResource(R.drawable.order_card);v.setOnClickListener(x->delivered(o.optString("id")));list.addView(v,new LinearLayout.LayoutParams(-1,-2));}history.removeAllViews();JSONArray h=d.optJSONArray("reset_history");if(h!=null)for(int i=0;i<h.length();i++){TextView v=new TextView(this);JSONObject x=h.optJSONObject(i);v.setText(x.optString("date_time")+" — "+x.optString("amount"));v.setPadding(8,8,8,8);history.addView(v);}onlineHistory.removeAllViews();JSONArray oh=d.optJSONArray("online_delivery_reset_history");if(oh!=null)for(int i=0;i<oh.length();i++){TextView v=new TextView(this);JSONObject x=oh.optJSONObject(i);v.setText(x.optString("date_time")+" — "+x.optString("amount"));v.setPadding(8,8,8,8);onlineHistory.addView(v);}}
 void delivered(String id){new AlertDialog.Builder(this).setTitle("Order delivered?").setPositiveButton("YES",(d,w)->new Thread(()->{try{ApiClient.post(this,AppConfig.DELIVERED,new JSONObject().put("order_id",id));load();}catch(Exception ignored){}}).start()).setNegativeButton("NO",null).show();}
 void resetOnlineDelivery(){new AlertDialog.Builder(this).setTitle("Online delivery charge paid/reset?").setMessage("Admin se online payment ka delivery charge milne ke baad hi reset karein.").setPositiveButton("PAID / RESET",(d,w)->new Thread(()->{try{ApiClient.post(this,AppConfig.RESET_ONLINE_DELIVERY,new JSONObject());load();}catch(Exception ignored){}}).start()).setNegativeButton("CANCEL",null).show();}
 void reset(){new AlertDialog.Builder(this).setTitle("Reset company cash total?").setPositiveButton("RESET",(d,w)->new Thread(()->{try{ApiClient.post(this,AppConfig.RESET,new JSONObject());load();}catch(Exception ignored){}}).start()).setNegativeButton("CANCEL",null).show();}
}
