package com.uklanafood.delivery;
import android.*;import android.app.*;import android.content.*;import android.content.pm.PackageManager;import android.graphics.Color;import android.os.*;import androidx.core.app.*;
public final class NotificationHelper{
 public static final String CHANNEL="ukf_delivery_orders_v2"; private NotificationHelper(){}
 public static void channel(Context c){if(Build.VERSION.SDK_INT>=26){NotificationChannel ch=new NotificationChannel(CHANNEL,"Delivery Orders",NotificationManager.IMPORTANCE_HIGH);ch.setDescription("Urgent Uklana Food delivery offers");ch.setSound(null,null);ch.enableVibration(true);ch.setBypassDnd(true);ch.setLockscreenVisibility(Notification.VISIBILITY_PUBLIC);((NotificationManager)c.getSystemService(Context.NOTIFICATION_SERVICE)).createNotificationChannel(ch);}}
 public static void show(Context c,String orderId,String title,String body){channel(c);RingtoneHelper.start(c);Intent a=new Intent(c,OrderAlertActivity.class).putExtra("order_id",orderId).putExtra("title",title).putExtra("message",body).addFlags(Intent.FLAG_ACTIVITY_NEW_TASK|Intent.FLAG_ACTIVITY_CLEAR_TOP);int id=Math.abs(orderId.hashCode());PendingIntent fs=PendingIntent.getActivity(c,id,a,PendingIntent.FLAG_UPDATE_CURRENT|PendingIntent.FLAG_IMMUTABLE);Intent ac=new Intent(c,OrderActionReceiver.class).setAction("ACCEPT").putExtra("order_id",orderId);Intent fw=new Intent(c,OrderActionReceiver.class).setAction("FORWARD").putExtra("order_id",orderId);NotificationCompat.Builder b=new NotificationCompat.Builder(c,CHANNEL).setSmallIcon(R.drawable.ic_app).setContentTitle(title).setContentText(body).setStyle(new NotificationCompat.BigTextStyle().bigText(body)).setPriority(NotificationCompat.PRIORITY_MAX).setCategory(NotificationCompat.CATEGORY_CALL).setVisibility(NotificationCompat.VISIBILITY_PUBLIC).setOngoing(true).setFullScreenIntent(fs,true).setContentIntent(fs).addAction(0,"ACCEPT",PendingIntent.getBroadcast(c,id+1,ac,PendingIntent.FLAG_UPDATE_CURRENT|PendingIntent.FLAG_IMMUTABLE)).addAction(0,"FORWARD",PendingIntent.getBroadcast(c,id+2,fw,PendingIntent.FLAG_UPDATE_CURRENT|PendingIntent.FLAG_IMMUTABLE)).setVibrate(new long[]{0,600,250,600}).setColor(Color.rgb(255,122,0));if(Build.VERSION.SDK_INT<33||ActivityCompat.checkSelfPermission(c,Manifest.permission.POST_NOTIFICATIONS)==PackageManager.PERMISSION_GRANTED)NotificationManagerCompat.from(c).notify(id,b.build());wake(c);}
 public static void cancel(Context c,String oid){RingtoneHelper.stop();NotificationManagerCompat.from(c).cancel(Math.abs(oid.hashCode()));}
 static void wake(Context c){try{PowerManager p=(PowerManager)c.getSystemService(Context.POWER_SERVICE);PowerManager.WakeLock w=p.newWakeLock(PowerManager.PARTIAL_WAKE_LOCK|PowerManager.ACQUIRE_CAUSES_WAKEUP,"UKF:Delivery");w.acquire(10000);}catch(Exception ignored){}}
}
